"""initial_uuid_schema

Revision ID: 149bc0e1eede
Revises: 
Create Date: 2026-04-07 00:55:02.308404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149bc0e1eede'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricas_plataforma',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha_metrica', sa.Date(), nullable=False),
    sa.Column('incidentes_totales', sa.Integer(), nullable=False),
    sa.Column('incidentes_resueltos', sa.Integer(), nullable=False),
    sa.Column('tiempo_resolucion_prom_min', sa.Float(), nullable=True),
    sa.Column('ingresos_totales', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('comisiones_totales', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('talleres_activos', sa.Integer(), nullable=False),
    sa.Column('usuarios_activos', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha_metrica')
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('hash_contrasena', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_table('talleres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('administrador_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('latitud', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('porcentaje_comision', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administrador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('propietario_id', sa.Uuid(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=60), nullable=False),
    sa.Column('modelo', sa.String(length=60), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['propietario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    op.create_table('incidentes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('vehiculo_id', sa.Uuid(), nullable=False),
    sa.Column('descripcion_texto', sa.Text(), nullable=True),
    sa.Column('latitud', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('clasificacion_ia', sa.String(length=50), nullable=True),
    sa.Column('confianza_ia', sa.Float(), nullable=True),
    sa.Column('resumen_ia', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metricas_taller',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('taller_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_metrica', sa.Date(), nullable=False),
    sa.Column('solicitudes_totales', sa.Integer(), nullable=False),
    sa.Column('solicitudes_aceptadas', sa.Integer(), nullable=False),
    sa.Column('solicitudes_completadas', sa.Integer(), nullable=False),
    sa.Column('tiempo_respuesta_prom_min', sa.Float(), nullable=True),
    sa.Column('ingresos_totales', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicios_taller',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('taller_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_servicio', sa.String(length=50), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnicos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('taller_id', sa.Uuid(), nullable=False),
    sa.Column('latitud_actual', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitud_actual', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('ubicacion_actualizada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incidente_id', sa.Uuid(), nullable=False),
    sa.Column('taller_id', sa.Uuid(), nullable=False),
    sa.Column('tecnico_id', sa.Uuid(), nullable=True),
    sa.Column('accion_taller', sa.String(length=20), nullable=True),
    sa.Column('taller_respondio_en', sa.DateTime(), nullable=True),
    sa.Column('eta_minutos', sa.Integer(), nullable=True),
    sa.Column('asignado_en', sa.DateTime(), nullable=False),
    sa.Column('completado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidencias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incidente_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('url_archivo', sa.String(length=500), nullable=True),
    sa.Column('transcripcion', sa.Text(), nullable=True),
    sa.Column('analisis_ia', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_servicio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incidente_id', sa.Uuid(), nullable=False),
    sa.Column('cambiado_por', sa.Uuid(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=20), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('cambiado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cambiado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incidente_id', sa.Uuid(), nullable=False),
    sa.Column('remitente_id', sa.Uuid(), nullable=False),
    sa.Column('rol_remitente', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ),
    sa.ForeignKeyConstraint(['remitente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('incidente_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=False),
    sa.Column('leida_en', sa.DateTime(), nullable=True),
    sa.Column('enviada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incidente_id', sa.Uuid(), nullable=False),
    sa.Column('monto_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('comision_plataforma', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('neto_taller', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('pagado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incidente_id'], ['incidentes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incidente_id')
    )
    op.create_table('turnos_tecnico',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tecnico_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_turno', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('en_servicio', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turnos_tecnico')
    op.drop_table('pagos')
    op.drop_table('notificaciones')
    op.drop_table('mensajes')
    op.drop_table('historial_servicio')
    op.drop_table('evidencias')
    op.drop_table('asignaciones')
    op.drop_table('tecnicos')
    op.drop_table('servicios_taller')
    op.drop_table('metricas_taller')
    op.drop_table('incidentes')
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_table('talleres')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('metricas_plataforma')
    # ### end Alembic commands ###
